languageCode = 'en-us'
title = 'Minecraft Bedrock Speedrunning'
theme = "minecraft"
copyright = 'Copyright @2024 Minecraft Speedrunning.'
enableGitInfo = true
enableRobotsTXT = true

[taxonomies]
  tag = 'tags'

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "Rules"
    name = "Rules"
    url = "/rules/"
    weight = 20
  [[menu.main]]
    identifier = "resources"
    name = "Resources"
    url = "/resources/"
    weight = 30
  [[menu.main]]
    identifier = "moderation"
    name = "Moderation"
    url = "/moderation/"
    weight = 40

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
