name = 'Minecraft'
license = 'MIT'
licenselink = 'https://github.com/mcbe-speedrunning/mcbe.wtf/LICENSE'
description = 'Hugo theme based on minecraft'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/mcbe-speedrunning/mcbe.wtf/'

# If you have a running demo of the theme
demosite = 'https://mcbe.wtf/'

# If the theme has multiple authors
authors = [
  {name = 'Luca Matei Pintilie', homepage = 'https://lucamatei.com/'},
]
